### ISSUE TITLE
ZFR review

### ISSUE THREAD

**Issue by talshi** [talshi/Yerushalmit#20]
@robi-y @ItamarShDev @guybi @AlumaK @gabrielaes @stavdv 
- Add functionality in the end of each iteration.
- What feature does the client will see in the end of each iteration?
- Iteration 1 plan.

**Comment by robi-y** [comment]
We also require a visual board so it is clear what is being worked right now and by whom. You need to detail for each iteration1 issue - the assignee and effort estimation - so you can some it up and learn about your velocity
