### ISSUE TITLE
project3-srs-submission-jerorg

### ISSUE THREAD

**Issue by talshi** [talshi/Yerushalmit#3]
SRS Document: https://github.com/talshi/jerorg/raw/master/project3-srs-submission-jerorg.docx
Git Code: https://github.com/talshi/jerorg
Wiki: https://github.com/talshi/jerorg/wiki
Distribution: http://jerusalemorg.azurewebsites.net/

@robi-y @ItamarShDev

**Comment by ItamarShDev** [comment]
:+1:
