### ISSUE TITLE
SRS fixes

### ISSUE THREAD

**Issue by talshi** [talshi/Yerushalmit#4]
Notes we got at the review:
- Remove from glossary unnecessary terms.
- Add plug-in use case.
- Success event - describe the process to reach success.
- Extensions - unexpected/undesirable actions.
- Hardware requirements - what server the organization use.
- Add a prototype of the plug-in (some example of how does it look).

@robi-y @ItamarShDev

**Comment by ItamarShDev** [comment]
:+1:
