### ISSUE TITLE
Iteration 1 Review

### ISSUE THREAD

**Issue by talshi** [talshi/Yerushalmit#41]
@ItamarShDev @robi-y

**Comment by ItamarShDev** [comment]
cant find your [code reviews](http://jce-il.github.io/se-class16b/morea/planning/experience-project6-iterations.html#section-14)
also cant see any [testing](http://jce-il.github.io/se-class16b/morea/planning/experience-project6-iterations.html#section-13)

**Comment by stavdv** [comment]
:+1: @ItamarShDev
