### ISSUE TITLE
Images for README

### ISSUE THREAD

**Issue by guybi** [talshi/Yerushalmit#5]
![seq](https://cloud.githubusercontent.com/assets/17545926/14061625/cb59063c-f395-11e5-8335-8d425136f16a.jpg)

**Comment by guybi** [comment]
![uml modeling](https://cloud.githubusercontent.com/assets/17545926/14061832/c80ada86-f39b-11e5-8b93-63dd345be031.jpg)

**Comment by gabrielaes** [comment]
![architecture](https://cloud.githubusercontent.com/assets/17564508/14064039/105ed488-f3f9-11e5-87d2-19c24474500d.png)
