### ISSUE TITLE
ZFR document

### ISSUE THREAD

**Issue by stavdv** [talshi/Yerushalmit#88]
Hi, 
In iteration 0, we have fixed: 
- Backlog:Issues & Board - we added issues as needed and during our work.
- Iteration 1 planning - we wrote it just after the review in class.
- We added expectations of the client as you recommended.
- Prototype - we did not make a prototype, we did the angularjs mission instead, everyone by himself. We understood that we can choose between the mockups and the angularjs mission.

Thank you.

@robi-y @ItamarShDev

**Comment by robi-y** [comment]
Please assign the TA to recheck

**Comment by ItamarShDev** [comment]
:+1:
